const mockMentors = [
  {
    id: 1,
    name: 'Aisha Patel',
    title: 'Senior Software Engineer',
    company: 'Stripe',
    industry: 'tech',
    bio: 'Full-stack engineer...',
    years_experience: 9,
    expertise: ['System Design', 'JavaScript', 'Career Growth', 'Interview Prep'],
    rating: 4.9,
    total_sessions: 87,
    session_price: 120,
    mentor_tier: 'Premium',
  },
  {
    id: 2,
    name: 'Marcus Webb',
    title: 'Investment Analyst',
    company: 'Blackstone',
    industry: 'finance',
    bio: 'I work on private equity...',
    years_experience: 7,
    expertise: ['Private Equity', 'Financial Modeling', 'Networking', 'Resume Review'],
    rating: 4.7,
    total_sessions: 54,
    session_price: 95,
    mentor_tier: 'Pro',
  },
  {
    id: 3,
    name: 'Dr. Lena Kim',
    title: 'Clinical Data Scientist',
    company: 'Mayo Clinic',
    industry: 'healthcare',
    bio: 'Bridging medicine...',
    years_experience: 11,
    expertise: ['Health Data', 'Python', 'Clinical Research', 'Career Transitions'],
    rating: 4.8,
    total_sessions: 63,
    session_price: 110,
    mentor_tier: 'Premium',
  },
  {
    id: 4,
    name: 'Jordan Rivers',
    title: 'Head of Growth',
    company: 'Notion',
    industry: 'marketing',
    bio: 'Growth marketer...',
    years_experience: 8,
    expertise: ['GTM Strategy', 'Content Marketing', 'Analytics', 'B2B SaaS'],
    rating: 4.6,
    total_sessions: 41,
    session_price: 80,
    mentor_tier: 'Starter',
  },
  {
    id: 5,
    name: 'Tariq Hassan',
    title: 'ML Engineer',
    company: 'DeepMind',
    industry: 'data science',
    bio: 'I work on reinforcement learning...',
    years_experience: 6,
    expertise: ['Machine Learning', 'Python', 'Research', 'Deep Learning'],
    rating: 4.9,
    total_sessions: 72,
    session_price: 130,
    mentor_tier: 'Premium',
  },
  {
    id: 6,
    name: 'Sofia Reyes',
    title: 'Product Manager',
    company: 'Figma',
    industry: 'tech',
    bio: 'I went from UX design...',
    years_experience: 5,
    expertise: ['Product Strategy', 'UX', 'Roadmapping', 'Career Pivots'],
    rating: 4.7,
    total_sessions: 39,
    session_price: 90,
    mentor_tier: 'Pro',
  },
  {
    id: 7,
    name: 'Daniel Osei',
    title: 'Venture Capital Associate',
    company: 'Sequoia Capital',
    industry: 'finance',
    bio: 'Former founder turned VC...',
    years_experience: 10,
    expertise: ['Venture Capital', 'Fundraising', 'Pitch Decks', 'Startup Strategy'],
    rating: 4.8,
    total_sessions: 58,
    session_price: 140,
    mentor_tier: 'Premium',
  },
  {
    id: 8,
    name: 'Priya Nair',
    title: 'Biotech Consultant',
    company: 'McKinsey & Company',
    industry: 'healthcare',
    bio: 'Healthcare strategy consultant...',
    years_experience: 12,
    expertise: ['Healthcare Strategy', 'Life Sciences', 'Consulting', 'Med-Tech'],
    rating: 4.6,
    total_sessions: 47,
    session_price: 115,
    mentor_tier: 'Premium',
  },
  {
    id: 9,
    name: 'Ethan Zhao',
    title: 'Data Engineering Lead',
    company: 'Snowflake',
    industry: 'data science',
    bio: 'I build data platforms...',
    years_experience: 8,
    expertise: ['Data Engineering', 'SQL', 'Cloud', 'dbt', 'Spark'],
    rating: 4.7,
    total_sessions: 66,
    session_price: 100,
    mentor_tier: 'Pro',
  },
  {
    id: 10,
    name: 'Camille Fontaine',
    title: 'Brand Strategist',
    company: 'LVMH',
    industry: 'marketing',
    bio: 'Luxury brand strategist...',
    years_experience: 14,
    expertise: ['Brand Strategy', 'Luxury Marketing', 'Storytelling', 'Personal Branding'],
    rating: 4.5,
    total_sessions: 33,
    session_price: 85,
    mentor_tier: 'Starter',
  },
  {
    id: 11,
    name: 'Ryan Nakamura',
    title: 'DevOps Engineer',
    company: 'Cloudflare',
    industry: 'tech',
    bio: 'I live in infrastructure...',
    years_experience: 7,
    expertise: ['Kubernetes', 'CI/CD', 'AWS', 'SRE', 'Observability'],
    rating: 4.8,
    total_sessions: 45,
    session_price: 105,
    mentor_tier: 'Pro',
  },
  {
    id: 12,
    name: 'Amara Diallo',
    title: 'UX Research Lead',
    company: 'Spotify',
    industry: 'tech',
    bio: 'Mixed-methods researcher...',
    years_experience: 9,
    expertise: ['UX Research', 'Inclusive Design', 'Qualitative Methods', 'Portfolio Review'],
    rating: 4.9,
    total_sessions: 79,
    session_price: 95,
    mentor_tier: 'Pro',
  },

  // 🔥 NEW MENTORS

  {
    id: 13,
    name: 'Lucas Meyer',
    title: 'AI Product Lead',
    company: 'OpenAI',
    industry: 'tech',
    bio: 'I work at the intersection of AI and product. I help people break into AI product roles and understand real-world ML applications.',
    years_experience: 8,
    expertise: ['AI Product', 'Machine Learning', 'Product Strategy'],
    rating: 4.9,
    total_sessions: 51,
    session_price: 150,
    mentor_tier: 'Premium',
  },
  {
    id: 14,
    name: 'Hannah Brooks',
    title: 'Startup Founder',
    company: 'YC-backed Startup',
    industry: 'startup',
    bio: 'Built and exited my first startup. I help founders validate ideas, pitch investors, and avoid early mistakes.',
    years_experience: 6,
    expertise: ['Startups', 'Pitching', 'Growth', 'Fundraising'],
    rating: 4.8,
    total_sessions: 44,
    session_price: 135,
    mentor_tier: 'Premium',
  },
  {
    id: 15,
    name: 'Omar Khalid',
    title: 'Cybersecurity Specialist',
    company: 'Google',
    industry: 'tech',
    bio: 'Security engineer focused on cloud systems and threat detection. I help engineers transition into cybersecurity roles.',
    years_experience: 9,
    expertise: ['Cybersecurity', 'Cloud Security', 'Networking'],
    rating: 4.7,
    total_sessions: 38,
    session_price: 110,
    mentor_tier: 'Pro',
  },
  {
    id: 16,
    name: 'Emily Carter',
    title: 'HR & Career Coach',
    company: 'LinkedIn',
    industry: 'career',
    bio: 'Career coach helping professionals optimize resumes, interviews, and personal branding.',
    years_experience: 10,
    expertise: ['Resume Review', 'Interview Prep', 'Personal Branding'],
    rating: 4.8,
    total_sessions: 60,
    session_price: 75,
    mentor_tier: 'Starter',
  },
];

export default mockMentors;