export const EN_CONTENT = {
  nav: {
    mentors: 'Mentors',
    dashboard: 'Dashboard',
    resume: 'Resume',
    pricing: 'Pricing',
    about: 'About',
    login: 'Log in',
    getStarted: 'Get started',
    getStartedFree: 'Get started free',
    findMentor: 'Find a Mentor',
    myProfile: 'My Profile',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Log out',
    mentorAccount: 'Mentor Account',
    memberAccount: 'Member Account',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
  },

  common: {
    close: 'Close',
    home: 'Home',
    sessions: 'Sessions',
    saved: 'Saved',
    billing: 'Billing',
    availability: 'Availability',
    earnings: 'Earnings',
    reviews: 'Reviews',
    hours: 'Hours',
    loading: 'Loading…',
    error: 'Something went wrong. Please try again.',
    save: 'Save',
    cancel: 'Cancel',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    retry: 'Retry',
  },

  dashboard: {
    skipToContent: 'Skip to content',
    expandSidebar: 'Expand sidebar',
    collapseSidebar: 'Collapse sidebar',
    pageMissingTitle: "That page doesn't exist.",
    pageMissingBody: 'Use the sidebar to navigate.',
    loadErrorTitle: "We couldn't load your dashboard.",
    loadErrorBody: "That's on us, not you.",
    retry: 'Retry',
    welcome: 'Welcome back',
    upcomingSessions: 'Upcoming Sessions',
    pastSessions: 'Past Sessions',
    pendingRequests: 'Pending Requests',
    favorites: 'Saved Mentors',
    noUpcoming: 'No upcoming sessions. Book one now!',
    noPast: 'No completed sessions yet.',
    noPending: 'No pending requests.',
    noFavorites: "You haven't saved any mentors yet.",
    joinCall: 'Join Call',
    cancelSession: 'Cancel',
    accept: 'Accept',
    decline: 'Decline',
    complete: 'Mark Complete',
    statusPending: 'Pending',
    statusAccepted: 'Accepted',
    statusDeclined: 'Declined',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
  },

  footer: {
    stayInLoop: 'Stay in the loop',
    newsletterBody: 'Mentor spotlights, career resources, product updates. No spam, ever.',
    subscribed: "You're subscribed!",
    subscribe: 'Subscribe',
    displayMode: 'Display mode',
    light: 'Light',
    system: 'System',
    dark: 'Dark',
    platform: 'Platform',
    company: 'Company',
    getInTouch: 'Get in touch',
    allSystemsOperational: 'All systems operational',
    rightsReserved: 'All rights reserved.',
    browseMentors: 'Browse Mentors',
    aiMatching: 'AI Matching',
    resumeReview: 'Resume Review',
    blog: 'Blog',
    careers: 'Careers',
    trustSafety: 'Trust & Safety',
    community: 'Community',
    privacy: 'Privacy',
    terms: 'Terms',
    cookies: 'Cookies',
    help: 'Help',
    contact: 'Contact',
    whyUs: 'Why Bridge',
  },

  auth: {
    checkingSession: 'Checking your session…',
    emailAddress: 'Email address',
    password: 'Password',
    confirm: 'Confirm',
    hidePassword: 'Hide password',
    showPassword: 'Show password',
    forgot: 'Forgot?',
    loginTitle: 'Welcome back',
    loginSubtitle: 'Step back into your mentor network with a focused, secure, beautifully crafted gateway.',
    signIn: 'Sign In',
    signingIn: 'Signing in…',
    noAccount: 'No account?',
    createOne: 'Create one',
    invalidEmail: 'Enter a valid email address.',
    shortPassword: 'Password must be at least 6 characters.',
    somethingWrong: 'Something went wrong. Please try again.',
    registerTitle: 'Create account',
    registerMentorTitle: 'Create mentor access',
    registerSubtitle: 'Launch a secure Bridge identity with role-aware onboarding, human trust signals, and a premium first impression.',
    alreadyHaveOne: 'Already have one?',
    signInLink: 'Sign in',
    fullName: 'Full name',
    passwordStrongPlaceholder: 'Strong password',
    repeatPasswordPlaceholder: 'Repeat password',
    findMentorTitle: 'Find a mentor',
    findMentorDesc: 'Browse, save, and book high-signal sessions.',
    beMentorTitle: 'Be a mentor',
    beMentorDesc: 'Build a trusted profile and receive requests.',
    createAccount: 'Create Account',
    createMentorAccount: 'Create mentor account',
    creatingAccount: 'Creating account…',
    signupAgreementPrefix: 'By signing up you agree to our',
    terms: 'Terms',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    browseMentors: 'Browse mentors',
    fullNameRequired: 'Please enter your full name.',
    validEmailRequired: 'Please enter a valid email address.',
    passwordsDoNotMatch: 'Passwords do not match.',
    chooseRole: 'Choose how you will use Bridge.',
  },

  settings: {
    languageRegion: 'Language & Region',
    language: 'Language',
    timezone: 'Timezone',
  },

  landing: {
    heroEyebrow: 'Now booking — 2,400+ mentors live this week',
    heroHeadline1: 'The fastest path',
    heroHeadline2: 'to your next role.',
    heroSubTagline: "Talk to someone who's already done it.",
    heroSubCopy: 'AI-matched to your exact goal. Booked in seconds — no subscriptions, no packages, no DMs.',
    heroCtaGetMatched: 'Get matched',
    heroCtaSeeHow: 'See how it works ↓',
    heroTrustNoCard: 'No credit card to browse',
    heroTrustBooked: 'Booked in 60 seconds',
    heroTrustRating: '/5 across 1,200+ sessions',

    statsHeading: 'By the numbers',
    statsVettedMentors: 'Vetted mentors',
    statsReviews: '1,200+ reviews',
    statsRecommend: 'Would recommend',
    statsCompIncrease: 'Comp increases unlocked',

    howEyebrow: 'How it works',
    howHeading1: 'Three steps.',
    howHeading2: 'Real momentum.',
    howSubCopy: 'From profile to booked session in under five minutes.',
    howStep1Title: 'Tell us what you need.',
    howStep1Body: 'Two questions, sixty seconds. Matching surfaces the right operators in real time.',
    howStep1Chip: 'Sixty seconds',
    howStep2Title: 'Pick someone who has done it.',
    howStep2Body: 'Real role, real company, real outcomes. Pricing, calendar, reviews on every profile.',
    howStep2Chip: 'Pick a slot',
    howStep3Title: 'Talk. Walk away with momentum.',
    howStep3Body: 'One hour, one focused conversation. Notes and action items stay with you after.',
    howStep3Chip: 'Live in one click',

    manifestoEyebrow: 'What we built differently',
    manifestoHeading1: 'Built differently,',
    manifestoHeading2: 'by design.',
    manifestoSubCopy: 'We started because every alternative was broken. This is what we fixed.',
    manifestoP1Title: "Only people who've done your job.",
    manifestoP1Body: "Every mentor has lived the exact role you're targeting. We filter on outcome, not credentials.",
    manifestoP2Title: 'One hour, one price.',
    manifestoP2Body: 'No packages. No lock-ins. No "contact us for pricing." Every rate on every profile, always.',
    manifestoP3Title: 'Booked in the time it takes to make coffee.',
    manifestoP3Body: 'Calendar-native. Real-time availability. No "when are you free" email loops, no scheduling assistants, no waiting two weeks for a reply.',
    manifestoP4Title: 'All reviews, unfiltered.',
    manifestoP4Body: 'Good and critical, side by side. No curation, no censoring, no removed posts.',

    comparisonEyebrow: 'Why not just DM on LinkedIn?',
    comparisonHeading1: 'What you tried',
    comparisonHeading2: 'before Bridge.',
    comparisonSubCopy: 'Three ways people try to fix their career. Each one wastes more time than it saves.',
    comparisonAlt1Label: 'LinkedIn cold DMs',
    comparisonAlt1Problem: 'Two replies out of fifty, three weeks later.',
    comparisonAlt1Tag: 'Slow + low signal',
    comparisonAlt2Label: 'Six-month coaching packages',
    comparisonAlt2Problem: '$1,200 commitment for a relationship that may not fit.',
    comparisonAlt2Tag: 'Expensive + over-committed',
    comparisonAlt3Label: 'Career courses and content',
    comparisonAlt3Problem: 'Generic advice. No one who has done your exact job.',
    comparisonAlt3Tag: 'Impersonal + abstract',
    comparisonInstead: 'Instead',
    comparisonBridgeHeadline: 'Bridge: one session, the right person.',
    comparisonBridgeSub: 'Booked in seconds. $60 average. No subscriptions. No DMs.',
    comparisonBridgeTag: 'Direct + decisive',

    outcomesHeading1: 'People who got',
    outcomesHeading2: 'unstuck.',
    outcomesSubCopy: 'Real outcomes from people who booked the session. We use first-name and role only.',

    showcaseEyebrow: "This week's spotlight",
    showcaseHeading1: 'One mentor,',
    showcaseHeading2: 'up close.',
    showcaseSubCopy: 'Every profile on Bridge looks like this — real bio, real numbers, real booking.',
    showcaseAbout: 'About',
    showcaseFocusAreas: 'Focus areas',
    showcaseRating: 'Rating',
    showcaseSessions: 'Sessions',
    showcaseOpenProfile: 'Open full profile',
    showcaseAlsoBooking: 'Also booking this week',
    showcaseCount: '5 of 2,400+ vetted mentors.',
    showcaseSeeEvery: 'See every mentor',

    pricingEyebrow: 'Pricing, clearly',
    pricingHeading1: 'No subscription to unlock mentors.',
    pricingHeading2: 'You pay per session.',
    pricingSubCopy: 'Browse free. Book the operator who fits. Pay once, walk away with momentum.',
    pricingSeeDetails: 'See pricing details',
    pricingFrom: 'From',
    pricingAvg: 'Avg',
    pricingUpto: 'Up to',
    pricingPer30min: 'per 30 min',
    pricingPerSession: 'per session',
    pricingSeniorMentors: 'senior mentors',
    pricingMost: 'Most',

    ctaBadge: 'Ready to get unstuck?',
    ctaHeading1: 'One conversation',
    ctaHeading2: 'changes everything.',
    ctaSubCopy: "Stop spinning. Book a session with someone who's walked the exact path you're on — and made it through.",
    ctaGetMatched: 'Get matched',
    ctaNoCard: 'No credit card',
    ctaNoCardSub: 'Sign up free · pay per session',
    ctaFirstSession: 'First session guaranteed',
    ctaFirstSessionSub: "Full refund if it isn't a fit",
    ctaCancelAnytime: 'Cancel any time',
    ctaCancelAnytimeSub: 'No subscriptions, ever',

    matchHeading: 'What do you want to figure out?',
    matchMatching: 'Matching against 2,400+ mentors…',
    matchTryDifferent: 'Try a different goal',
    matchPerSession: '/ session',
  },

  pricing: {
    heroEyebrow: 'Pick your plan — no card to start',
    heroHeading1: 'Simple pricing,',
    heroHeading2: 'pick what fits.',
    heroSubCopy: "Subscription plans cover Bridge platform access. Mentor sessions are paid separately at each mentor's rate.",
    billingMonthly: 'Monthly',
    billingAnnual: 'Annual',
    trustRating: '4.9 / 5 from',
    trustUsers: '+ users',
    trustNoCard: 'No card for Free tier',
    trustCancel: 'Cancel any time',
    trustStripe: 'Stripe-secured checkout',
    studentTitle: 'Student discount applied — 50% off any plan',
    studentNotLoggedInHint: 'Register with your',
    studentEduEmail: '.edu email',
    studentUnlockHint: 'to unlock 50% off any subscription plan automatically.',
    studentLabel: 'Student?',
    perMonth: '/month',
    forever: 'Forever · no card required',
    sessionNote: 'Mentor sessions are not included in the subscription price.',
    sessionNoteBottom: "Mentor sessions are paid separately during booking based on each mentor's rate.",
    compareEyebrow: 'Side-by-side',
    compareHeading: 'Compare',
    compareHeadingItalic: 'plans',
    compareSub: 'Bridge platform features, side by side.',
    compareFeature: 'Feature',
    compareBest: 'Best',
    mentorTiersBadge: 'How Bridge categorizes mentors',
    mentorTiersHeading: 'Mentor',
    mentorTiersHeadingItalic: 'tiers',
    mentorTiersSub: "Each mentor is placed in a tier based on their experience and seniority. Session rates are set by each mentor individually and shown on their profile — not by Bridge.",
    mentorTiersPerHour: 'per hour · algorithm-assigned',
    mentorTiersExperience: 'experience',
    browseMentorsByTier: 'Browse mentors by tier',
    freeTaglineMentor: 'Run sessions on Bridge',
    freeTaglineMentee: 'Explore the platform',
    freeCtaUser: 'Current plan',
    freeCtaGuest: 'Sign up free',
    paymentSuccess: 'Subscription payment successful. Your plan is now active.',
    paymentLoginFirst: 'Please log in before subscribing.',
    paymentCannotStart: 'Could not start checkout.',
    paymentCannotConnect: 'Could not connect to payment server.',
    paymentCannotVerify: 'Could not verify payment.',
  },

  mentors: {
    heroEyebrowBrowse: 'Browse the Bridge mentor directory',
    heroHeading1: "Find the mentor who's",
    heroHeading2: 'already done it',
    heroSubCopy: 'Vetted founders, executives, and specialists. Search, filter, book in 60 seconds.',
    aiMatch: 'AI match',
    aiMatchUsedUp: 'AI matching used up',
    compareTiers: 'Compare tiers',
    searchPlaceholder: 'Search by name, role, company…',
    filters: 'Filters',
    filtersTier: 'Tier',
    filtersRate: 'Rate / session',
    filtersStatus: 'Status',
    filtersAvailableNow: 'Available now',
    filtersClear: 'Clear',
    sortLabel: 'Sort',
    showing: 'Showing',
    of: 'of',
    filtered: '· filtered',
    prev: '← Prev',
    next: 'Next →',
    previous: '← Previous',
    page: 'Page',
    noResultsHeading: 'Nobody fits that combo',
    noResultsSub: 'Try loosening a filter or using a different keyword.',
    noResultsReset: 'Reset filters',
    asMentorBanner: "You're signed in as a mentor.",
    asMentorDashboard: 'Open your dashboard →',
    errorTitle: "Mentors didn't load",
    errorRetry: 'Retry',
    aiHeading: 'Your top mentor matches.',
    aiEyebrow: 'AI-Powered Matches',
    aiGoal: 'Goal:',
    aiIn: 'in',
    aiRetake: 'Retake',
    aiBrowseAll: '← Browse all',
    aiHonorable: 'Honorable Mentions',
    aiLoading: 'Finding your best mentors…',
    aiLoadingSub: 'Our AI is reviewing all profiles for you.',
    aiError: 'Something went wrong.',
    aiRetry: 'Retry',
  },
  pricing: {
    heroEyebrow: 'Transparent pricing, always',
    heroHeading1: 'Invest in your career.',
    heroHeading2: 'Not in subscriptions.',
    heroSubCopy: 'Pick the plan that fits your pace. Upgrade, downgrade, or cancel anytime — no lock-ins, no hidden fees.',
    billingMonthly: 'Monthly',
    billingAnnual: 'Annual',
    trustNoCard: 'No card required to browse',
    trustCancel: 'Cancel anytime',
    trustStripe: 'Secured by Stripe',
    studentTitle: 'Student discount — 50% off automatically applied',
  },
};
