export const EN_CONTENT = {
  nav: {
    mentors: 'Mentors',
    dashboard: 'Dashboard',
    resume: 'Resume',
    pricing: 'Pricing',
    about: 'About',
    company: 'Company',
    login: 'Log in',
    getStarted: 'Get started',
    getStartedFree: 'Get started free',
    findMentor: 'Find a Mentor',
    myProfile: 'My Profile',
    profile: 'Profile',
    settings: 'Settings',
    logout: 'Log out',
    mentorAccount: 'Mentor Account',
    memberAccount: 'Member Account',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
  },

  common: {
    close: 'Close',
    home: 'Home',
    sessions: 'Sessions',
    saved: 'Saved',
    billing: 'Billing',
    availability: 'Availability',
    earnings: 'Earnings',
    reviews: 'Reviews',
    hours: 'Hours',
    loading: 'Loading…',
    error: 'Something went wrong. Please try again.',
    save: 'Save',
    cancel: 'Cancel',
    back: 'Back',
    next: 'Next',
    submit: 'Submit',
    edit: 'Edit',
    delete: 'Delete',
    confirm: 'Confirm',
    retry: 'Retry',
    saving: 'Saving…',
    continue: 'Continue',
    done: 'Done',
    remove: 'Remove',
    add: 'Add',
    view: 'View',
    open: 'Open',
    download: 'Download',
    upload: 'Upload',
    preview: 'Preview',
    search: 'Search',
    filter: 'Filter',
    clear: 'Clear',
    reset: 'Reset',
    present: 'Present',
    unknown: 'Unknown',
    optional: 'optional',
    required: 'Required',
    backToDashboard: 'Back to Dashboard',
    leaveReview: 'Leave a Review',
    joinCall: 'Join Call',
    bookSession: 'Book a Session',
    viewProfile: 'View profile',
    contactSupport: 'Contact support',
    questions: 'Questions?',
  },

  dashboard: {
    skipToContent: 'Skip to content',
    expandSidebar: 'Expand sidebar',
    collapseSidebar: 'Collapse sidebar',
    pageMissingTitle: "That page doesn't exist.",
    pageMissingBody: 'Use the sidebar to navigate.',
    loadErrorTitle: "We couldn't load your dashboard.",
    loadErrorBody: "That's on us, not you.",
    retry: 'Retry',
    welcome: 'Welcome back',
    upcomingSessions: 'Upcoming Sessions',
    pastSessions: 'Past Sessions',
    pendingRequests: 'Pending Requests',
    favorites: 'Saved Mentors',
    noUpcoming: 'No upcoming sessions. Book one now!',
    noPast: 'No completed sessions yet.',
    noPending: 'No pending requests.',
    noFavorites: "You haven't saved any mentors yet.",
    joinCall: 'Join Call',
    cancelSession: 'Cancel',
    accept: 'Accept',
    decline: 'Decline',
    complete: 'Mark Complete',
    statusPending: 'Pending',
    statusAccepted: 'Accepted',
    statusDeclined: 'Declined',
    statusCompleted: 'Completed',
    statusCancelled: 'Cancelled',
    // page subtitles
    sessionsSubtitle: 'Past, upcoming, and pending.',
    hoursSubtitle: 'Set when mentees can book you.',
    earningsSubtitle: 'Tracked nightly. Paid weekly.',
    reviewsSubtitle: 'All feedback from your sessions.',
    billingSubtitle: 'Your payment history.',
    settingsSubtitle: 'Preferences and account options.',
    profileSubtitle: 'Your public mentor profile.',
    savedSubtitle: 'Mentors you have saved.',
    // home header sublines
    sessionLiveNow: 'You have a session live right now.',
    sessionStartsSoon: 'Your next session starts {countdown}.',
    bookingWaiting: 'Your booking is waiting on a time. Check your email to schedule.',
    openHours: 'Open your hours so mentees can book you.',
    readyToBook: 'Ready to book your next hour?',
    // home actions
    openProfile: 'Open profile',
    setAvailability: 'Set availability',
    browseMentors: 'Browse mentors',
    // no availability banner
    noAvailabilityBanner: "Connect your booking calendar — mentees can't book you yet.",
    openAvailability: 'Open availability',
    // earnings page
    earningsNoCompletedYet: 'No completed sessions yet — this is where your payouts will show up.',
    earningsDate: 'Date',
    earningsMentee: 'Mentee',
    earningsType: 'Type',
    earningsAmount: 'Amount',
    earningsGoToEarnings: 'Open Earnings',
    earningsMentorNote: 'Mentor earnings live in the Earnings tab.',
    // billing
    billingAwaitingMentor: 'Awaiting mentor',
    billingConfirmed: 'Confirmed',
    billingCompleted: 'Completed',
    // sessions page statuses
    timeTbd: 'Time TBD · awaiting mentor',
    timeSyncing: 'Time syncing from Calendly',
    timeCancelled: 'Cancelled — no time',
    timeDeclined: 'Declined — no time',
    // verification banner
    verifyTitle: 'Verify your mentor account.',
    verifyBody: 'Mentees see verified mentors first. Earn your tier in ~10 minutes.',
    verifyCta: 'Start',
    verifyInProgressTitle: 'Pick up where you left off.',
    verifyInProgressBody: "You're at {score}/100. Finish the remaining steps to lock in your tier.",
    verifyInProgressCta: 'Continue',
    verifyRejectedTitle: 'Verification was rejected.',
    verifyRejectedBody: 'Re-run the wizard with stronger evidence to be re-considered.',
    verifyRejectedCta: 'Retry',
    verifySuspendedTitle: 'Your mentor account is suspended.',
    verifySuspendedBody: 'Contact Bridge support to restore access.',
    verifySuspendedCta: 'Details',
    // tier explainer
    verificationTier: 'Verification tier',
    continueVerification: 'Continue verification',
    reVerify: 'Re-verify',
    ptsToNextTier: '+{gap} pts to {tier}',
    fastestPaths: '— fastest paths:',
    atHighestTier: "You're at the highest tier. Keep your sessions strong to stay there.",
    // profile health
    profileCompletion: 'Profile completion',
    completeMentorProfile: 'Complete your mentor profile so mentees can find and book you.',
    completeProfile: 'A complete profile helps mentors understand what you need.',
    // sessions actions
    reviewSession: 'Leave a Review',
    reviewed: 'Reviewed',
    now: 'Now',
    today: 'Today',
    tomorrow: 'Tomorrow',
    // next session card
    justStarted: 'Just started',
    startedAgo: 'Started {mins} minute ago',
    startedAgoPlural: 'Started {mins} minutes ago',
    sessionLive: 'live',
    waitingOnTime: 'awaiting',
    // recommendations
    recommendedMentors: 'Recommended for you',
    seeAllMentors: 'See all →',
  },

  footer: {
    stayInLoop: 'Stay in the loop',
    newsletterBody: 'Mentor spotlights, career resources, product updates. No spam, ever.',
    subscribed: "You're subscribed!",
    subscribe: 'Subscribe',
    displayMode: 'Display mode',
    light: 'Light',
    system: 'System',
    dark: 'Dark',
    platform: 'Platform',
    company: 'Company',
    getInTouch: 'Get in touch',
    allSystemsOperational: 'All systems operational',
    rightsReserved: 'All rights reserved.',
    browseMentors: 'Browse Mentors',
    aiMatching: 'AI Matching',
    resumeReview: 'Resume Review',
    blog: 'Blog',
    careers: 'Careers',
    trustSafety: 'Trust & Safety',
    community: 'Community',
    privacy: 'Privacy',
    terms: 'Terms',
    cookies: 'Cookies',
    help: 'Help',
    contact: 'Contact',
    whyUs: 'Why Bridge',
    // FAQ page
    faqEyebrow: 'Help center',
    faqHeadingLine1: 'Questions,',
    faqHeadingItalic: 'answered',
    faqSearchPlaceholder: 'Search questions…',
    faqAll: 'All',
    faqNoResults: 'No questions match your search.',
    // Contact page
    contactHeading: 'Get in touch',
    contactSubCopy: 'Our team is here to help.',
    contactNameLabel: 'Your name',
    contactEmailLabel: 'Email address',
    contactTopicLabel: 'Topic',
    contactMessageLabel: 'Message',
    contactSendCta: 'Send message',
    contactSending: 'Sending…',
    contactSentHeading: 'Message received',
    contactSentBody: "We'll get back to you within 24 hours.",
    contactTicketLabel: 'Ticket number',
    contactReplyNote: 'Keep this for replies.',
    contactEmailLabel2: 'Email',
    contactEmailSecondary: 'Reply within 24 hours',
    contactPhoneLabel: 'Phone',
    contactPhoneSecondary: 'Mon–Fri, 9am–6pm PT',
    contactOfficeLabel: 'Office',
  },

  auth: {
    checkingSession: 'Checking your session…',
    emailAddress: 'Email address',
    password: 'Password',
    confirm: 'Confirm',
    hidePassword: 'Hide password',
    showPassword: 'Show password',
    forgot: 'Forgot?',
    loginTitle: 'Welcome back',
    loginSubtitle: 'Step back into your mentor network with a focused, secure, beautifully crafted gateway.',
    signIn: 'Sign In',
    signingIn: 'Signing in…',
    noAccount: 'No account?',
    createOne: 'Create one',
    invalidEmail: 'Enter a valid email address.',
    shortPassword: 'Password must be at least 6 characters.',
    somethingWrong: 'Something went wrong. Please try again.',
    registerTitle: 'Create account',
    registerMentorTitle: 'Create mentor access',
    registerSubtitle: 'Launch a secure Bridge identity with role-aware onboarding, human trust signals, and a premium first impression.',
    alreadyHaveOne: 'Already have one?',
    signInLink: 'Sign in',
    fullName: 'Full name',
    passwordStrongPlaceholder: 'Strong password',
    repeatPasswordPlaceholder: 'Repeat password',
    findMentorTitle: 'Find a mentor',
    findMentorDesc: 'Browse, save, and book high-signal sessions.',
    beMentorTitle: 'Be a mentor',
    beMentorDesc: 'Build a trusted profile and receive requests.',
    createAccount: 'Create Account',
    createMentorAccount: 'Create mentor account',
    creatingAccount: 'Creating account…',
    signupAgreementPrefix: 'By signing up you agree to our',
    terms: 'Terms',
    and: 'and',
    privacyPolicy: 'Privacy Policy',
    browseMentors: 'Browse mentors',
    fullNameRequired: 'Please enter your full name.',
    validEmailRequired: 'Please enter a valid email address.',
    passwordsDoNotMatch: 'Passwords do not match.',
    chooseRole: 'Choose how you will use Bridge.',
  },

  settings: {
    languageRegion: 'Language & Region',
    language: 'Language',
    timezone: 'Timezone',
    notifications: 'Notifications',
    emailNotifications: 'Email notifications',
    pushNotifications: 'Push notifications',
    theme: 'Theme',
    account: 'Account',
    deleteAccount: 'Delete account',
    saveChanges: 'Save changes',
    changesSaved: 'Changes saved',
  },

  profile: {
    // section labels
    sectionPersonal: 'Personal',
    sectionResume: 'Résumé',
    sectionExperience: 'Experience',
    sectionEducation: 'Education',
    sectionSkills: 'Skills',
    sectionAchievements: 'Achievements',
    sectionMentor: 'Mentor Profile',
    // personal info
    personalInfoHeading: 'Personal Information',
    fullName: 'Full Name',
    professionalTitle: 'Professional Title',
    bio: 'Bio',
    bioPlaceholder: 'Tell us about yourself…',
    email: 'Email',
    phone: 'Phone',
    location: 'Location',
    website: 'Website',
    linkedin: 'LinkedIn',
    github: 'GitHub',
    // resume
    resumeHeading: 'Résumé / CV',
    resumeDescription: 'Upload a PDF or Word file. It is stored privately; share the preview or download link when you apply or book sessions.',
    noFileUploaded: 'No file uploaded yet.',
    uploadPdfOrWord: 'Upload PDF or Word',
    replaceFile: 'Replace file',
    uploading: 'Uploading…',
    uploadError: 'Please upload a PDF or Word document.',
    resumeUploaded: 'Résumé uploaded and saved.',
    resumeRemoved: 'Résumé removed.',
    linkUnavailable: 'Link unavailable',
    preparingLink: 'Preparing link…',
    // experience
    workExperienceHeading: 'Work Experience',
    addExperience: 'Add Experience',
    noExperienceYet: 'No work experience added yet',
    addFirstExperience: 'Add your first experience',
    company: 'Company',
    position: 'Position',
    startDate: 'Start Date',
    endDate: 'End Date',
    currentlyWorkingHere: 'Currently working here',
    description: 'Description',
    descriptionPlaceholder: 'Describe your responsibilities and achievements…',
    // education
    educationHeading: 'Education',
    addEducation: 'Add Education',
    noEducationYet: 'No education added yet',
    addYourEducation: 'Add your education',
    school: 'School',
    degree: 'Degree',
    fieldOfStudy: 'Field of Study',
    gpa: 'GPA',
    currentlyStudyingHere: 'Currently studying here',
    // skills
    skillsHeading: 'Skills',
    noSkillsYet: 'No skills added yet — type below to add your first one',
    skillInputPlaceholder: 'Type a skill and press Enter or Add…',
    // achievements
    achievementsHeading: 'Achievements',
    addAchievement: 'Add Achievement',
    noAchievementsYet: 'No achievements added yet',
    addFirstAchievement: 'Add your first achievement',
    achievementTitle: 'Title',
    achievementDate: 'Date',
    achievementDescriptionPlaceholder: 'Describe your achievement…',
    // mentor profile tab
    mentorProfileHeading: 'Mentor Profile',
    mentorProfileDescription: 'This information appears on your public mentor listing that mentees browse.',
    displayName: 'Display Name',
    jobTitle: 'Job Title',
    industry: 'Industry',
    yearsOfExperience: 'Years of Experience',
    sessionRate: 'Session Rate (USD/hr)',
    sessionRateNote: 'Set algorithmically · dispute from dashboard',
    bioAbout: 'Bio / About',
    bioAboutPlaceholder: 'Describe your experience and what you can help mentees with…',
    profileImageUrl: 'Profile Image URL',
    tier: 'Tier',
    tierNote: 'Set algorithmically · dispute from dashboard',
    availableForSessions: 'Available for new sessions',
    areasOfExpertise: 'Areas of Expertise',
    expertisePlaceholder: 'e.g. Product Strategy, Career Growth…',
    noExpertiseYet: 'No expertise areas added yet',
    // save states
    saveChanges: 'Save changes',
    saving: 'Saving…',
    profileSaved: 'Profile saved successfully!',
    mentorProfileSaved: 'Mentor profile saved!',
    // preview / resume view
    resumePreviewHeading: 'Resume Preview',
    resumePreviewSubtitle: 'This is how mentors will see your profile',
    saveAsPdf: 'Save as PDF',
    editProfile: 'Edit Profile',
    aboutSection: 'About',
    workExperienceSection: 'Work Experience',
    educationSection: 'Education',
    skillsSection: 'Skills',
    achievementsSection: 'Achievements',
    linksSection: 'Links',
    // completion bar
    profileCompletionLabel: 'Profile completion',
    completeMentorPrompt: 'Complete your mentor profile so mentees can find and book you.',
    completeMenteePrompt: 'A complete profile helps mentors understand what you need.',
    // role badge
    mentorBadge: 'Mentor',
    memberBadge: 'Member',
  },

  resumeReview: {
    // breadcrumb
    breadcrumbLabel: 'Resume Review',
    // hero
    aiPoweredBadge: 'AI-Powered',
    heading: 'AI Resume Review',
    subCopy: 'Get an honest, detailed grade on your resume from our AI career coach — with specific rewrite suggestions to help you stand out.',
    // limit reached
    limitReachedTitle: "You've used your free resume review.",
    limitReachedBody: 'Each account receives one free AI review.',
    // step 1
    step1Heading: 'Step 1 — Experience Level',
    step1Sub: 'This lets our AI grade you against the right benchmark.',
    entryLevel: 'Entry Level',
    entryLevelRange: '0–2 yrs',
    entryLevelDesc: 'Recent grads, career changers, and those just getting started.',
    midLevel: 'Mid Level',
    midLevelRange: '3–7 yrs',
    midLevelDesc: 'Building expertise, taking on more ownership and scope.',
    seniorLevel: 'Senior Level',
    seniorLevelRange: '8+ yrs',
    seniorLevelDesc: 'Deep expertise, leadership, and staff-to-executive roles.',
    selected: 'Selected',
    // step 2
    step2Heading: 'Step 2 — Upload Your Resume',
    step2Sub: 'PDF only · max 5 MB · text-based (not a scanned image)',
    dropzoneText: 'Drop your PDF here, or',
    dropzoneBrowse: 'click to browse',
    dropzoneNote: 'PDF only · max 5 MB',
    removeFile: 'Remove file',
    // cta
    freeReviewNote: '1 free resume review per account',
    analyzeCta: 'Analyze My Resume',
    privacyNote: 'Your resume is stored privately and only used to generate your review.',
    // loading messages
    loadingReading: 'Reading your resume…',
    loadingExperience: 'Evaluating your experience section…',
    loadingFormatting: 'Checking formatting and structure…',
    loadingScore: 'Calculating your score…',
    loadingSuggestions: 'Writing improvement suggestions…',
    loadingTimer: 'This takes about 15–30 seconds',
    // results
    gradedAs: 'Graded as:',
    gradeEntryLong: 'Entry Level (0–2 yrs)',
    gradeMidLong: 'Mid Level (3–7 yrs)',
    gradeSeniorLong: 'Senior Level (8+ yrs)',
    sectionBreakdown: 'Section Breakdown',
    rewriteSuggestions: 'Rewrite Suggestions',
    showRewriteSuggestions: 'Show rewrite suggestions',
    hideRewriteSuggestions: 'Hide rewrite suggestions',
    // section labels
    sectionContactInfo: 'Contact Info',
    sectionSummary: 'Summary / Objective',
    sectionExperience: 'Work Experience',
    sectionSkills: 'Skills',
    sectionEducation: 'Education',
    sectionFormatting: 'Formatting & Structure',
    // actions
    readyToImproveHeading: 'Ready to improve your score?',
    readyToImproveSub: 'Work with a mentor who can give you hands-on feedback — or upload a revised resume to see your progress.',
    findMentorCta: 'Find a Mentor to Help Improve This',
    uploadNewCta: 'Upload a New Resume',
    clearingText: 'Clearing…',
    lastAnalyzed: 'Last analyzed:',
    // errors
    apiErrorRetry: 'Your file is still selected — click "Analyze My Resume" to try again.',
    cannotReadFile: 'Could not read the file. Please try again.',
    storageSaveError: 'Resume could not be saved to storage, but your review is ready.',
    reviewSaveError: 'Review could not be saved to your account, but is shown below.',
    onlyPdf: 'Only PDF files are accepted.',
    fileTooLarge: 'File is too large ({size} MB). Max is 5 MB.',
    pleaseSelectFile: 'Please select a file.',
  },

  videoCall: {
    // pre-join
    readyToJoin: 'Ready to join?',
    sessionWith: '{type} with {name}',
    cameraOff: 'Camera off',
    microphone: 'Microphone',
    camera: 'Camera',
    joinMeeting: 'Join Meeting',
    youAreHost: 'You are the host of this session',
    youAreParticipant: 'You are joining as a participant',
    // in-call chat
    inMeetingChat: 'In-meeting chat',
    noMessages: 'No messages yet',
    messagePlaceholder: 'Message…',
    // mentor review modal
    rateMentee: 'Rate this mentee',
    rateMenteePrivate: 'Private — never visible to anyone except admins.',
    // session type labels
    careerAdvice: 'Career Advice',
    interviewPrep: 'Interview Prep',
    resumeReview: 'Resume Review',
    networking: 'Networking',
    // error state
    cameraAccessDenied: 'Camera/mic access denied — you can still join audio-only.',
    couldNotAccessCamera: 'Could not access camera or microphone.',
  },

  intakeCall: {
    // header
    intakeBadge: '{type} · Intake',
    sessionWith: 'Session with {name}',
    intakeIntro: "Before your session, we'd like to learn a bit about you so your mentor can hit the ground running.",
    intakeIntroAlt: 'Before your session, answer a few short questions to help your mentor prepare.',
    // text fallback
    questionOf: 'Question {current} of {total}',
    typeYourAnswer: 'Type your answer below',
    answerPlaceholder: 'Your answer...',
    ctrlEnterHint: 'Ctrl+Enter to continue',
    nextQuestion: 'Next question →',
    submitBriefing: 'Submit & generate briefing',
    // states
    tapToSpeak: 'Tap to speak',
    sessionLive: 'Session live',
    listening: 'Listening...',
    processing: 'Processing...',
    connecting: 'Connecting...',
    connectingToBridgeAI: 'Connecting to Bridge AI',
    settingUpVoice: 'Setting up your voice session...',
    bridgeAISpeaking: 'Bridge AI is speaking...',
    listeningToYou: 'Listening to you...',
    endSession: 'End Session',
    useTextInstead: 'Use text instead',
    totalQuestions: '{total} questions',
    readyMessage: 'Ready when you are. We\'ll ask you a few short questions — just speak naturally.',
    // processing
    generatingBriefing: 'Generating mentor briefing...',
    justAMoment: 'This will just take a moment',
    // complete
    allDone: 'All done!',
    mentorPrepared: 'Your mentor will be prepared for your session.',
    // already done
    alreadyCompletedHeading: "You've already completed your intake",
    alreadyCompletedBody: 'Your mentor is ready for your session.',
    // no support
    voiceNotSupportedHeading: 'Voice input not supported',
    voiceNotSupportedBody: "Your browser doesn't support voice input. Please use Chrome or Edge.",
    // conversation
    conversationWillAppear: 'Your conversation will appear here...',
    live: 'Live',
  },

  onboarding: {
    // screen titles (MentorOnboarding)
    applyTitle: 'Apply to become a mentor',
    applySub: 'Tell us about your professional background.',
    verifyTitle: 'Verify your identity',
    verifySub: 'We verify all mentors to keep Bridge trustworthy.',
    motivationTitle: 'Why do you want to mentor?',
    motivationSub: 'This essay is scored algorithmically.',
    completeProfileTitle: 'Complete your profile',
    completeProfileSub: "Your application was approved. You're almost live.",
    skillsTitle: 'Skills & presence',
    skillsSub: 'Help mentees find the right match.',
    // buttons
    continue: 'Continue',
    processing: 'Processing…',
    back: 'Back',
    // work experience
    jobTitle: 'Job title',
    company: 'Company',
    startYear: 'Start year',
    endYear: 'End year',
    oneLineDescription: 'One-line description',
    removeEntry: 'Remove',
    addJobCta: '+ Add job',
    // education
    schoolLabel: 'School / Institution *',
    fieldOfStudy: 'Field of study',
    degreeLevel: 'Degree level *',
    selectLevel: 'Select level…',
    graduationYear: 'Graduation year',
    diplomaUpload: 'Diploma / transcript upload',
    diplomaUploadHint: 'Upload diploma, transcript, or certificate (JPEG, PNG, PDF)',
    // degree levels
    degreePhd: 'PhD / Doctorate',
    degreeMasters: 'Masters (MBA, MS, MA, MEng…)',
    degreeBachelors: 'Bachelors (BA, BS, BEng…)',
    degreeAssociate: 'Associate / Diploma',
    degreeOther: 'Other / Certification',
    // profile preview
    perSession: 'Per session',
    aboutLabel: 'About',
    expertiseLabel: 'Expertise',
    experienceLabel: 'Experience',
    educationLabel: 'Education',
    detailsLabel: 'Details',
    languagesLabel: 'Languages',
    yearsLabel: '{n} years',
    // score panel
    likelyApproved: 'Likely approved',
    mayNeedReview: 'May need review',
    lowAddMoreInfo: 'Low — add more info',
    // phase 2 profile
    displayName: 'Display Name',
    jobTitleLabel: 'Job Title',
    industryLabel: 'Industry',
    locationLabel: 'Location',
    bioLabel: 'Bio',
    expertiseTagsLabel: 'Expertise tags',
    languagesTagsLabel: 'Languages',
    profileImageUrl: 'Profile Image URL',
    draftBioWithAI: 'Draft with AI',
    draftingBio: 'Drafting…',
    // application pending / rejected
    applicationPending: 'Awaiting Background Check',
    applicationPendingTitle: 'Your application is under review.',
    applicationPendingBody: "We've received your profile and triggered a background check via Checkr. This typically takes 1–3 business days. You'll be notified once it's complete.",
    applicationUnderReview: 'In Admin Review',
    applicationUnderReviewTitle: 'Background check passed.',
    applicationUnderReviewBody: 'Your background check came back clear. Our team is now reviewing your application. Approvals typically happen within 1 business day.',
    applicationRejected: 'Application Not Approved',
    applicationRejectedTitle: "We couldn't approve your application.",
    applicationRejectedBody: 'Unfortunately your application did not pass our verification process at this time. If you believe this is an error, please contact support.',
    applicationSuspended: 'Account Suspended',
    applicationSuspendedTitle: 'Your account has been suspended.',
    applicationSuspendedBody: 'Please contact our support team for more information about your account status.',
    // progress steps
    stepApplicationSubmitted: 'Application submitted',
    stepBackgroundCheck: 'Background check complete',
    stepAdminReview: 'Admin review',
    stepInProgress: 'In progress',
    stepDone: 'Done',
    editApplication: 'Edit my application',
    updateAndReapply: 'Update application & re-apply',
    editApplicationHint: 'You can update your work history, education, LinkedIn URL, or essay before your application is reviewed.',
    updateApplicationHint: 'Improve your verification score by adding work experience, education, a stronger LinkedIn URL, and a more detailed motivation essay.',
  },

  onboardingVerify: {
    // wizard shell
    verifyEyebrow: 'Mentor verification',
    verifyHeading: 'Earn your tier on Bridge',
    verifySubCopy: 'Complete each step at your pace. Higher-quality evidence = higher tier = more discovery + better rates.',
    // step labels
    stepWelcome: 'Welcome',
    stepIdentity: 'Identity',
    stepGovId: 'Government ID',
    stepProEmail: 'Work email',
    stepLinkedIn: 'Profile',
    stepResume: 'Resume',
    stepInterview: 'Interview',
    stepRefs: 'References',
    stepReview: 'Review',
    // welcome step
    welcomeHeading: 'Welcome to Bridge mentor verification',
    welcomeBody: 'Bridge is a paid marketplace. Mentees expect verified, accountable experts. We score your evidence across 8 components and place you in a tier — Bronze, Silver, Gold, or Platinum. Higher tiers unlock featured placement and stronger pricing bands.',
    expectation1Title: '~10 minutes for Silver',
    expectation1Body: 'Identity, professional email, resume.',
    expectation2Title: '~30 minutes for Gold',
    expectation2Body: 'Plus LinkedIn, the AI interview, and references.',
    expectation3Title: 'Manual review for Platinum',
    expectation3Body: 'Strong evidence + human admin verification.',
    beginVerification: 'Begin verification',
    // review step
    yourTierHeading: 'Your tier',
    yourTierSub: "Here's how each component contributed.",
    goToDashboard: 'Go to dashboard',
    reRunAStep: 'Re-run a step',
    finalizing: 'Finalizing…',
    // review step component labels
    reviewLabelIdentity: 'Identity',
    reviewLabelGovId: 'Government ID',
    reviewLabelProEmail: 'Professional email',
    reviewLabelLinkedIn: 'LinkedIn / portfolio',
    reviewLabelResume: 'Resume',
    reviewLabelInterview: 'Domain interview',
    reviewLabelReference: 'References',
    reviewLabelTrackRecord: 'Track record',
    pillPassed: 'Passed',
    pillFailed: 'Failed',
    pillReview: 'Review',
    pillPending: 'Pending',
    // identity step
    identityHeading: 'Verify your identity',
    identityVerified: 'Identity verified',
    identityVerifiedBody: 'Your phone number and email are confirmed.',
    mobileNumber: 'Mobile number',
    emailOptional: 'Email (optional)',
    sendOtp: 'Send OTP',
    sending: 'Sending…',
    verifying: 'Verifying…',
    verify: 'Verify',
    // gov id step
    govIdHeading: 'Upload government ID + selfie',
    govIdVerified: 'Government ID verified',
    govIdVerifiedBody: 'Your ID and selfie matched.',
    idFront: 'ID front',
    selfie: 'Selfie',
    submitting: 'Submitting…',
    // professional email step
    proEmailHeading: 'Verify your professional email',
    proEmailVerified: 'Professional email verified',
    workEmail: 'Work email',
    sendMagicLink: 'Send magic link',
    sendingMagicLink: 'Sending magic link…',
    confirmEmail: 'Confirm email',
    confirming: 'Confirming…',
    // linkedin step
    linkedInHeading: 'LinkedIn or portfolio',
    linkedInVerified: 'Profile verified',
    profileUrl: 'Profile URL',
    claimedTitle: 'Claimed title',
    claimedCompany: 'Claimed company',
    aiEvaluation: 'AI evaluation',
    evaluating: 'Evaluating…',
    // resume step
    resumeHeading: 'Upload your resume',
    resumeEvaluated: 'Resume evaluated',
    resumeContent: 'Resume content (paste or summary)',
    scoring: 'Scoring…',
    submitResume: 'Submit resume',
    // interview step
    interviewHeading: '3-minute domain interview',
    interviewScored: 'Interview scored',
    claimedExpertise: 'Claimed expertise',
    interviewTranscript: 'Interview transcript (3 short Q&A is enough)',
    aiRubric: 'AI rubric',
    submitInterview: 'Submit interview',
    // references step
    referencesHeading: 'Invite references',
    referenceEmail: 'Reference email',
    referenceName: 'Name (optional)',
    relationship: 'Relationship',
    sendInvite: 'Send invite',
    inviting: 'Inviting…',
    noReferencesYet: 'No references yet. Invite at least 2 to qualify for Gold or higher.',
    skipForNow: 'Skip for now',
    // bootstrap error
    needMentorProfile: 'You need a mentor profile before you can verify. Finish onboarding first.',
    couldNotStartVerification: 'Could not start verification',
    checkingAccount: 'Checking your account.',
    pleaseSignIn: 'Please sign in',
    signInBody: 'You need to be signed in as a mentor to verify.',
    goToSignIn: 'Go to sign in',
    cantStartVerification: "We can't start verification yet",
    goToOnboarding: 'Go to onboarding',
    loadingVerification: 'Loading verification…',
    settingUpRun: 'Setting up your run.',
    saveAndExit: 'Save & exit',
  },

  admin: {
    verificationQueue: 'Verification Queue',
    reviewApplication: 'Review Application',
    approve: 'Approve',
    reject: 'Reject',
    suspend: 'Suspend',
    requestMoreInfo: 'Request more info',
    submitReferenceEyebrow: 'Bridge reference',
    submitReferenceHeading: "Speak to this mentor's work",
    submitReferenceSub: 'Your honest feedback helps us tier mentors fairly. Specifics beat generic praise.',
    submitReferenceThanks: 'Thanks!',
    submitReferenceRecorded: 'Your reference has been recorded. You can close this page.',
    commentsLabel: 'Comments',
    submitReferenceInvalid: 'Invalid link',
    submitReferenceMinLength: 'Please write at least 20 characters.',
    submitReferenceCta: 'Submit reference',
    noApplications: 'No applications pending.',
    applicationDetails: 'Application Details',
    applicantName: 'Applicant Name',
    submittedAt: 'Submitted',
    verificationScore: 'Verification Score',
    status: 'Status',
  },

  mentors: {
    heroEyebrowBrowse: 'Browse the Bridge mentor directory',
    heroHeading1: "Find the mentor who's",
    heroHeading2: 'already done it',
    heroSubCopy: 'Vetted founders, executives, and specialists. Search, filter, book in 60 seconds.',
    aiMatch: 'AI match',
    aiMatchUsedUp: 'AI matching used up',
    compareTiers: 'Compare tiers',
    searchPlaceholder: 'Search by name, role, company…',
    filters: 'Filters',
    filtersTier: 'Tier',
    filtersRate: 'Rate / session',
    filtersStatus: 'Status',
    filtersAvailableNow: 'Available now',
    filtersClear: 'Clear',
    sortLabel: 'Sort',
    showing: 'Showing',
    of: 'of',
    filtered: '· filtered',
    prev: '← Prev',
    next: 'Next →',
    previous: '← Previous',
    page: 'Page',
    noResultsHeading: 'Nobody fits that combo',
    noResultsSub: 'Try loosening a filter or using a different keyword.',
    noResultsReset: 'Reset filters',
    asMentorBanner: "You're signed in as a mentor.",
    asMentorDashboard: 'Open your dashboard →',
    errorTitle: "Mentors didn't load",
    errorRetry: 'Retry',
    aiHeading: 'Your top mentor matches.',
    aiEyebrow: 'AI-Powered Matches',
    aiGoal: 'Goal:',
    aiIn: 'in',
    aiRetake: 'Retake',
    aiBrowseAll: '← Browse all',
    aiHonorable: 'Honorable Mentions',
    aiLoading: 'Finding your best mentors…',
    aiLoadingSub: 'Our AI is reviewing all profiles for you.',
    aiError: 'Something went wrong.',
    aiRetry: 'Retry',
    // AI match card
    aiMatchScore: '{score}% match',
    whyThisMentor: 'Why this mentor?',
    totalSessions: '{n} sessions',
    viewProfile: 'View profile',
    // tiers modal
    mentorTiersHeading: 'Mentor Tiers',
    mentorTiersSub: 'Every mentor on Bridge is placed in one of four tiers based on experience and expertise.',
    bridgePlatform: 'Bridge Platform',
    // match wizard
    wizardStep: 'Step {current} of {total}',
    currentPositionLabel: 'Current position / situation',
    targetRoleLabel: 'Target role',
    targetIndustryLabel: 'Target industry',
    topGoalsLabel: 'Top goals (pick up to 3)',
    sessionTypesLabel: 'Session types you need',
    availabilityLabel: 'Your availability',
    bioSummaryLabel: 'Brief summary (optional)',
    uploadResumeLabel: 'Upload your resume (optional)',
    findMyMentors: 'Find My Mentors',
    finding: 'Finding matches…',
  },

  mentorProfile: {
    allMentors: 'All mentors',
    // hero
    joinedLabel: 'Joined {date}',
    sessionsCompleted: '{n} sessions',
    ratingLabel: '{rating} rating',
    bookNow: 'Book now',
    savedToFavorites: 'Saved',
    saveToFavorites: 'Save',
    shareCopied: 'Copied!',
    share: 'Share',
    available: 'Available',
    unavailable: 'Unavailable',
    // booking drawer
    selectSessionType: 'Select session type',
    messagePlaceholder: 'What would you like to focus on?',
    requestSession: 'Request Session',
    requestingSession: 'Requesting…',
    loginToBook: 'Log in to book',
    mentorMentorCannotBook: "You're a mentor — you can't book other mentors.",
    // sections
    aboutHeading: 'About',
    expertiseHeading: 'Expertise',
    experienceHeading: 'Experience',
    educationHeading: 'Education',
    reviewsHeading: 'Reviews',
    comparableHeading: 'Similar mentors',
    // reviews
    noReviewsYet: 'No reviews yet.',
    outOf5: '/ 5',
    seeAllReviews: 'See all reviews',
    // track record
    trackRecordHeading: 'Track record',
    // checkout
    completePayment: 'Complete payment',
    closeCheckout: 'Close checkout',
  },

  pricing: {
    heroEyebrow: 'PRICING',
    heroHeading1: 'One plan. Everything included.',
    heroHeading2: '',
    heroSubCopy: 'Mentor sessions are always free — mentors volunteer their time. Your subscription unlocks AI tools, unlimited bookings, community, and everything we build next.',
    billingMonthly: 'Monthly',
    billingAnnual: 'Annual',
    trustRating: '4.9 / 5 from',
    trustUsers: '+ users',
    trustNoCard: 'No card for Free tier',
    trustCancel: 'Cancel any time',
    trustStripe: 'Stripe-secured checkout',
    studentTitle: 'Student discount applied — 50% off any plan',
    studentNotLoggedInHint: 'Register with your',
    studentEduEmail: '.edu email',
    studentUnlockHint: 'to unlock 50% off any subscription plan automatically.',
    studentLabel: 'Student?',
    perMonth: '/month',
    forever: 'Forever · no card required',
    sessionNote: 'Volunteer sessions — always free.',
    sessionNoteBottom: 'Mentors volunteer their time. Subscriptions pay for AI tools and platform features only.',
    compareSub: 'Sessions stay free on every plan. Compare what Plus and Pro unlock for AI matching, resume review, and booking workflow.',
    compareEyebrow: 'Side-by-side',
    compareHeading: 'Compare',
    compareHeadingItalic: 'plans',
    compareFeature: 'Feature',
    compareBest: 'Best',
    mentorTiersBadge: 'How Bridge categorizes mentors',
    mentorTiersHeading: 'Mentor',
    mentorTiersHeadingItalic: 'tiers',
    mentorTiersSub: "Each mentor is placed in a tier based on their experience and seniority. Session rates are set by each mentor individually and shown on their profile — not by Bridge.",
    mentorTiersPerHour: 'per hour · algorithm-assigned',
    mentorTiersExperience: 'experience',
    browseMentorsByTier: 'Browse mentors by tier',
    freeTaglineMentor: 'Run sessions on Bridge',
    freeTaglineMentee: 'Explore the platform',
    freeCtaUser: 'Current plan',
    freeCtaGuest: 'Sign up free',
    paymentSuccess: 'Subscription payment successful. Your plan is now active.',
    paymentLoginFirst: 'Please log in before subscribing.',
    paymentCannotStart: 'Could not start checkout.',
    paymentCannotConnect: 'Could not connect to payment server.',
    paymentCannotVerify: 'Could not verify payment.',
    // sticky bar
    mostPopularPlan: 'Most popular plan',
    billedAnnually: 'billed annually',
    cancelAnytime: 'cancel anytime',
    choosePro: 'Choose Pro',
    // faq
    faqHeading: 'Common',
    faqHeadingItalic: 'questions',
    // booking finalize
    almostThere: 'Almost there',
    pickYourHour: 'Pick your hour',
    chooseTimeWith: 'Choose a time that works for you with {name}.',
    bookingErrorHeading: "We couldn't open your booking link.",
    bookingErrorBody: 'Your payment was processed. Email {email} with your session id {id} and we will set it up by hand.',
    openDashboard: 'Open dashboard',
  },

  notifications: {
    heading: 'Notifications',
    noNotifications: 'No notifications yet.',
    refresh: 'Refresh',
    // mentor notifications
    newSessionRequest: 'New session request',
    newSessionRequestBody: '{name} requested a {type} session{date}.',
    sessionCancelled: 'Session cancelled',
    sessionCancelledBody: '{name} cancelled the {type} session{date}.',
    // mentee notifications
    sessionConfirmed: 'Session confirmed',
    sessionConfirmedBody: 'Your {type} session has been confirmed{date}.',
    sessionDeclined: 'Session declined',
    sessionDeclinedBody: 'Your {type} session was declined{date}.',
    // time helpers
    justNow: 'just now',
    minutesAgo: '{n}m ago',
    hoursAgo: '{n}h ago',
    daysAgo: '{n}d ago',
    // action labels
    viewSession: 'View session',
    acceptDecline: 'Accept / Decline',
  },

  reviews: {
    heading: 'Leave a Review',
    subCopy: 'How was your session with {name}?',
    ratingLabel: 'Rate {index} out of 5',
    commentPlaceholder: 'Share your experience (optional)…',
    submitReview: 'Submit Review',
    submitting: 'Submitting…',
    thankYou: 'Thank you!',
    thankYouBody: 'Your review has been submitted.',
    alreadyReviewed: 'You have already reviewed this session.',
    errorSelectRating: 'Please select a star rating before submitting.',
    errorAlreadyReviewed: 'You have already reviewed this session.',
    errorGeneric: 'Something went wrong. Please try again.',
    ratingLabels: {
      1: 'Poor',
      2: 'Fair',
      3: 'Good',
      4: 'Great',
      5: 'Excellent',
    },
  },

  cancellation: {
    heading: 'Cancel Session',
    sessionWith: 'Session with {name}',
    reasonLabel: 'Reason for cancellation',
    detailsLabel: 'Additional details (optional)',
    detailsPlaceholder: 'Anything else you want to share?',
    submitCta: 'Submit Cancellation',
    submitting: 'Submitting…',
    // limit
    limitWarning: "You've used all {limit} cancellations this month.",
    cancellationsRemaining: '{n} of {limit} cancellations remaining this month.',
    // reasons
    reasonSchedulingConflict: 'Scheduling conflict',
    reasonPersonalEmergency: 'Personal emergency',
    reasonNoLongerNeeded: 'Session no longer needed',
    reasonFoundAlternative: 'Found another mentor / mentee',
    reasonTechnicalIssues: 'Technical issues',
    reasonOther: 'Other',
    // success
    requestSent: 'Request sent',
    requestSentBody: "A developer will review and process your request. You'll be notified of the outcome.",
    // error
    selectReason: 'Please select a reason.',
  },

  about: {
    // hero
    eyebrow: 'About Bridge',
    heroHeading1: 'We built',
    heroHeading2: 'the platform',
    heroHeading3: 'we wished existed.',
    heroSubCopy: 'Bridge started because every other mentorship tool was broken. Anonymous experts, hidden pricing, weeks of scheduling back-and-forth — we fixed all of it.',
    // principles
    principlesEyebrow: 'Principles',
    principlesHeading1: 'How we make',
    principlesHeading2: 'every decision.',
    principlesSub: 'Four rules we use to settle every product, hiring, and pricing call.',
    // origin
    originEyebrow: 'Origin story',
    // team
    teamEyebrow: 'Team',
    teamHeading: 'The people behind Bridge.',
    // timeline
    timelineEyebrow: 'Timeline',
    // contact CTA
    contactCtaHeading: 'Want to get in touch?',
    contactCtaSub: "We read every message. If you're a mentor, mentee, investor, or just curious — we'd love to hear from you.",
    contactCtaButton: 'Contact us',
  },

  whyUs: {
    // hero
    eyebrow: 'Why Bridge',
    heroHeading1: 'The mentorship platform',
    heroHeading2: 'built differently.',
    heroSubCopy: 'Three things that make Bridge categorically different from everything else out there.',
    // statements (contrarian beliefs)
    contrarianEyebrow: 'Contrarian beliefs',
    // side by side
    sideBySideEyebrow: 'What changed',
    sideBySideHeading1: 'Before Bridge.',
    sideBySideHeading2: 'After Bridge.',
    // receipts
    receiptsEyebrow: 'Receipts',
    receiptsHeading1: 'Real outcomes,',
    receiptsHeading2: 'real numbers.',
    // mechanism
    mechanismEyebrow: 'How it works',
    // commitments
    commitmentsHeading1: 'Four commitments,',
    commitmentsHeading2: 'in writing.',
    // audience
    audienceEyebrow: "Who it's for",
    audienceHeading: 'Built for people who are serious about their career.',
    // final CTA
    finalCtaHeading1: 'Ready to talk to someone',
    finalCtaHeading2: "who's been there?",
    finalCtaSub: 'Find your mentor in 60 seconds. No subscription required.',
    finalCtaButton: 'Browse mentors',
    finalCtaSecondary: 'Read more about how it works',
  },

  landing: {
    heroEyebrow: 'Now booking — 2,400+ mentors live this week',
    heroHeadline1: 'The fastest path',
    heroHeadline2: 'to your next role.',
    heroSubTagline: "Talk to someone who's already done it.",
    heroSubCopy: 'AI-matched to your exact goal. Booked in seconds — no subscriptions, no packages, no DMs.',
    heroCtaGetMatched: 'Get matched',
    heroCtaSeeHow: 'See how it works ↓',
    heroTrustNoCard: 'No credit card to browse',
    heroTrustBooked: 'Booked in 60 seconds',
    heroTrustRating: '/5 across 1,200+ sessions',
  },
};
